import { useState } from 'react';
import { useRouter } from 'next/router';
import { useAuth } from '../context/AuthContext';
import LoginForm from '../components/LoginForm';

const SERVICE_CATEGORIES = [
  'Peinture intérieure',
  'Réparation de gypse',
  'Escalier métallique extérieur',
  'Terrasse sablage et teinture',
  'Clôture',
  'Cuisine Ikea',
  'Peinture d\'armoires',
  'Petites rénovations',
  'Service homme à tout faire',
  'Préparation avant hiver',
  'Réparations extérieures',
];

const PLATFORMS = [
  { value: 'facebook',   label: 'Facebook' },
  { value: 'instagram',  label: 'Instagram' },
  { value: 'gbp',        label: 'Google Business Profile' },
  { value: 'linkedin',   label: 'LinkedIn' },
  { value: 'website',    label: 'Website / Gallery' },
  { value: 'ad',         label: 'Ad concept' },
  { value: 'email_sms',  label: 'Email / SMS' },
];

const LANGUAGES = [
  { value: 'fr',        label: 'Français' },
  { value: 'en',        label: 'English' },
  { value: 'bilingual', label: 'Bilingual' },
];

const TONES = [
  { value: 'professional',  label: 'Professional' },
  { value: 'friendly',      label: 'Friendly' },
  { value: 'local',         label: 'Local / Neighbourly' },
  { value: 'premium',       label: 'Premium' },
  { value: 'educational',   label: 'Educational' },
  { value: 'urgent',        label: 'Urgent / Seasonal' },
  { value: 'trust',         label: 'Trust-building' },
  { value: 'before_after',  label: 'Before / After Showcase' },
];

const CTAS = [
  { value: 'request_quote',   label: 'Request a quote' },
  { value: 'book_spring',     label: 'Book spring work' },
  { value: 'book_winter',     label: 'Book before winter' },
  { value: 'visit_website',   label: 'Visit website' },
  { value: 'call_message',    label: 'Call / message us' },
  { value: 'ask_availability',label: 'Ask about availability' },
  { value: 'leave_review',    label: 'Leave a review' },
  { value: 'see_projects',    label: 'See more projects' },
];

const DEFAULT_FORM = {
  service_category: SERVICE_CATEGORIES[0],
  platform: 'facebook',
  language: 'fr',
  tone: 'professional',
  job_description: '',
  city: 'Montréal',
  cta: 'request_quote',
};

function ResultCard({ result, onSave, saving }) {
  const [edited, setEdited] = useState({ ...result });

  return (
    <div className="card mt-6 border-l-4 border-accent-500">
      <div className="flex items-center justify-between mb-4">
        <h3 className="font-semibold text-gray-800">Generated Content — {edited.title}</h3>
        <button className="btn-primary" onClick={() => onSave(edited)} disabled={saving}>
          {saving ? 'Saving…' : 'Save to Publishing Queue'}
        </button>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label className="label">Main Copy</label>
          <textarea
            className="input h-36 resize-y"
            value={edited.main_copy}
            onChange={(e) => setEdited({ ...edited, main_copy: e.target.value })}
          />
        </div>
        <div>
          <label className="label">Short Variation</label>
          <textarea
            className="input h-36 resize-y"
            value={edited.short_variation}
            onChange={(e) => setEdited({ ...edited, short_variation: e.target.value })}
          />
        </div>
        <div>
          <label className="label">Hashtags</label>
          <input
            className="input"
            value={edited.hashtags}
            onChange={(e) => setEdited({ ...edited, hashtags: e.target.value })}
          />
        </div>
        <div>
          <label className="label">Call to Action</label>
          <input
            className="input"
            value={edited.cta}
            onChange={(e) => setEdited({ ...edited, cta: e.target.value })}
          />
        </div>
        {edited.notes && (
          <div className="col-span-full">
            <label className="label">Notes</label>
            <p className="text-sm text-orange-600 bg-orange-50 rounded-lg p-3">{edited.notes}</p>
          </div>
        )}
        {result.ai_used === false && (
          <div className="col-span-full bg-yellow-50 border border-yellow-200 rounded-lg p-3 text-sm text-yellow-800">
            ⚠ No AI provider is configured — this is a template-based draft. Go to{' '}
            <a href="/settings" className="underline font-medium">Settings → AI Provider</a> to enable real AI generation.
          </div>
        )}
        {result.ai_used === true && (
          <div className="col-span-full bg-green-50 border border-green-200 rounded-lg p-2 text-xs text-green-700">
            ✓ Generated by AI
          </div>
        )}
      </div>
    </div>
  );
}

export default function SocialStudioPage() {
  const { isLoggedIn, apiFetch } = useAuth();
  const router = useRouter();
  const [form, setForm] = useState(DEFAULT_FORM);
  const [result, setResult] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  const generate = async (e) => {
    e.preventDefault();
    setGenerating(true); setError(''); setResult(null);
    const r = await apiFetch('/social/generate', { method: 'POST', body: JSON.stringify(form) });
    if (r.ok) {
      const data = await r.json();
      setResult(data);
    } else {
      let msg = 'Generation failed.';
      try { const d = await r.json(); msg = d.detail || msg; } catch {}
      if (r.status === 502) msg = `AI provider error: ${msg}`;
      if (r.status === 400) msg = `Configuration issue: ${msg}`;
      setError(msg);
    }
    setGenerating(false);
  };

  const saveDraft = async (edited) => {
    setSaving(true);
    await apiFetch('/publishing/drafts', {
      method: 'POST',
      body: JSON.stringify({
        title: edited.title,
        platform: form.platform,
        language: form.language,
        tone: form.tone,
        service_category: form.service_category,
        body: edited.main_copy,
        short_body: edited.short_variation,
        hashtags: edited.hashtags,
        cta: edited.cta,
        status: 'draft_generated',
      }),
    });
    setSaving(false);
    router.push('/publishing');
  };

  if (!isLoggedIn) return <LoginForm />;

  return (
    <div className="p-6 max-w-4xl">
      <h2 className="text-2xl font-bold text-gray-900 mb-1">AI Social Studio</h2>
      <p className="text-gray-500 text-sm mb-6">
        Turn recent work into platform-ready social content. Review before saving.
      </p>

      <div className="card">
        <h3 className="font-semibold text-gray-800 mb-4 flex items-center gap-2">
          <span>✨</span> Create content from recent work
        </h3>
        <form onSubmit={generate} className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <label className="label">Service Category</label>
            <select
              className="select"
              value={form.service_category}
              onChange={(e) => setForm({ ...form, service_category: e.target.value })}
            >
              {SERVICE_CATEGORIES.map((c) => <option key={c} value={c}>{c}</option>)}
            </select>
          </div>
          <div>
            <label className="label">Platform</label>
            <select
              className="select"
              value={form.platform}
              onChange={(e) => setForm({ ...form, platform: e.target.value })}
            >
              {PLATFORMS.map(({ value, label }) => <option key={value} value={value}>{label}</option>)}
            </select>
          </div>
          <div>
            <label className="label">Language</label>
            <select
              className="select"
              value={form.language}
              onChange={(e) => setForm({ ...form, language: e.target.value })}
            >
              {LANGUAGES.map(({ value, label }) => <option key={value} value={value}>{label}</option>)}
            </select>
          </div>
          <div>
            <label className="label">Tone</label>
            <select
              className="select"
              value={form.tone}
              onChange={(e) => setForm({ ...form, tone: e.target.value })}
            >
              {TONES.map(({ value, label }) => <option key={value} value={value}>{label}</option>)}
            </select>
          </div>
          <div>
            <label className="label">City / Neighbourhood</label>
            <input
              className="input"
              value={form.city}
              onChange={(e) => setForm({ ...form, city: e.target.value })}
              placeholder="Montréal, Plateau-Mont-Royal…"
            />
          </div>
          <div>
            <label className="label">Call to Action</label>
            <select
              className="select"
              value={form.cta}
              onChange={(e) => setForm({ ...form, cta: e.target.value })}
            >
              {CTAS.map(({ value, label }) => <option key={value} value={value}>{label}</option>)}
            </select>
          </div>
          <div className="col-span-full">
            <label className="label">Job Description</label>
            <textarea
              className="input h-24 resize-y"
              value={form.job_description}
              onChange={(e) => setForm({ ...form, job_description: e.target.value })}
              placeholder="Brief description of the work done. E.g. Repainted salon walls in Benjamin Moore Swiss Coffee, fixed two small drywall cracks…"
            />
          </div>
          {error && <p className="col-span-full text-sm text-red-600">{error}</p>}
          <div className="col-span-full flex gap-3">
            <button type="submit" className="btn-primary" disabled={generating}>
              {generating ? 'Generating…' : 'Generate Content Pack'}
            </button>
            <button
              type="button"
              className="btn-secondary"
              onClick={() => setForm(DEFAULT_FORM)}
            >
              Reset
            </button>
          </div>
        </form>
      </div>

      {result && (
        <ResultCard result={result} onSave={saveDraft} saving={saving} />
      )}
    </div>
  );
}
